baseURL: "https://johanneshollenbach.com/"
title: Johannes Hollenbach
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: CV
          url: files/hollenbach_cv.pdf
          weight: 3

params:
    description: "Personal website of Johannes Hollenbach, economist at RWI - Leibniz Institute for Economic Research: research papers, teaching, CV, and contact information."
    author: Johannes Hollenbach
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: []
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Johannes Hollenbach
          subtitle: |-
            I am a PhD candidate in Economics at Paderborn University and a researcher at RWI - Leibniz Institute for Economic Research in Essen, Germany. My main fields are applied econometrics and health economics, with a focus on health effects of education, the economics of aging, and social science genetics.

            I was a visitor at [UW-Madison](https://isg.wisc.edu/people/) in Fall 2024 and at [WU Vienna](https://www.wu.ac.at/en/institute-for-social-policy/) in Fall 2021.
          imageUrl: images/profile_picture.jpg
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: CV
              url: files/hollenbach_cv.pdf

    socialIcons:
        - name: Email
          url: mailto:johannes.hollenbach@rwi-essen.de
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=hasnrIwAAAAJ&hl=en
        - name: LinkedIn
          url: https://www.linkedin.com/in/johannes-hollenbach

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Johannes Hollenbach
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2